### ISSUE TITLE
Use proper python 3.7 for travis and cache pip dependencies

### ISSUE THREAD

**Issue by janehmueller** [janehmueller/python-json-config#24]
For python 3.7 to work with travis the build needs to run on xenial (Ubuntu 16.04) instead of trusty (Ubuntu 14.04) and require sudo. [(reference)](https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-401756442).

The travis file should have the following
```
python:
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
```

Also add caching for pip dependencies:
```
cache: pip
```
